name: Metrics
on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: bigass metrics
        uses: lowlighter/metrics@latest
        with:
          # Output
          filename: bigass.svg
          
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: yeniferrosana
          template: classic
          base: header, activity, community, repositories
          config_display: large
          config_padding: 0, 3%
          plugin_traffic: yes
